### PR TITLE
Feature:  Buy/Sell now returns confirmation about the agent, player, …

### PR DESCRIPTION
**Pull request by kennethtran93**
Feature:  Buy/Sell now returns confirmation about the agent, player, price, and balance remaining.  

Also, for human readability, transactions and certificate datetime value is now set to display YYYY-MM-DD HH:MM:SS.  luckily the db datetime column is just big enough to store this string format - exactly 19 characters long :)

Probably better to return the peanuts remaining to the agent...

Signed-off-by:Kenneth Tran <kennethtran93@gmail.com>

### CODE REVIEW

**Comment by XCVG** [comment]
According to a Facebook post, this may be a breaking change. I haven't checked it myself yet, but @kennethtran93 stated that it would require all agents to be updated.

**Comment by kennethtran93** [comment]
Preview of proposed change output to Buy Controller

mozilla firefox

**Comment by XCVG** [comment]
I just checked it. The datetime changes alone make this addition pointless and dangerous.

Human readability in datetime is unimportant; PHP can handle UNIX timestamps just fine, you shouldn't be storing datetime as a string in a database, and formatting should be handled by the client, not the master server. It will break all existing clients, and for what?

**Comment by kennethtran93** [comment]
the server backend is already storing datetime as varchar(19), so that instance it's just a direct output to the user.

**Comment by kennethtran93** [comment]
the breaking point would be the parsing of the return response.

**Comment by kennethtran93** [comment]
basically the current output would be enclosed in a new parent element.  Inside the parent element would return a billto section confirming the agent/player, price, and peanut balance remaining

**Comment by kennethtran93** [comment]
The sell controller output would just have its parent node renamed, with additional elements to confirm agent, player, and balance of peanuts.

**Comment by XCVG** [comment]
Without going into why the server is storing datetime as something other than datetime or timestamp...

Yes, it would break any agent that assumes that a UNIX timestamp will be returned. That's the exact point of contention I have with this. It's a change of dubious benefit to new agents that breaks existing ones.

The other changes I haven't looked at in enough depth to argue for or against it, but in general, breaking changes are a bad thing. Improvements are good but not when other things rely on your service.

**Comment by kennethtran93** [comment]
I suppose I could change the datetime value back to time() and adjust the output in the controller as a workaround...

**Comment by kennethtran93** [comment]
datetime has been reverted back to storing time().  Attempted to convert using controllers instead.  I can't test that as my migrated mssql server is using datetime and not varchar.

**Comment by kennethtran93** [comment]
Correction on the sell controller - just new elements added, parent node was not renamed.

**Comment by kennethtran93** [comment]
Unfortunately for the Buy controller, I cannot make it backwards-compatible otherwise it's not a properly formated xml output.

**Comment by kennethtran93** [comment]
Just remembered that we could possibly use attributes as well... So there may not be any breaking changes after all...

**Comment by kennethtran93** [comment]
With this it shouldn't break any existing working agents.

mozilla firefox

**Comment by jim-parry** [comment]
Sorry - I have been under the weather, and unable to check this out.
The latest change seems to preserve backwards-compability, so we'll give it a go!

**Comment by jim-parry** [comment]
deployed to botcards.jlparry.com

**Pull request merged**
